version: '3'

services:
    front-end:
        restart: "unless-stopped"
        container_name: "dash-label"
        build: 
            context: 'front/'
            dockerfile: 'docker/Dockerfile'
        command: 'python src/labelmaker.py'
        environment:
            DATA_DIR: "${PWD}/data/"
        volumes:
            - "./data:/app/work/data"
            - "./front/src:/app/work/src"
        ports:
            - '8057:8057'
        networks:
            - computing_api_default

    api:
        restart: "unless-stopped"
        container_name: "labelmaker-api"
        build:
          context: "api/"
          dockerfile: "docker/Dockerfile"
        volumes:
          - ./api/src:/app/api/src
        ports:
          - "8005:8005"
        networks:
          - computing_api_default

networks:
  computing_api_default:
    external: true