version: '3.7'

x-environment: &commonEnvironment
    DATA_DIR: "${PWD}/data/"
    PROJECT_ID: "-1"
    MLCOACH_URL: "http://localhost:8062"
    DATA_CLINIC_URL: "http://localhost:8072"
    SPLASH_URL: "http://splash:80/api/v0"
    MLEX_COMPUTE_URL: "http://job-service:8080/api/v0"
    MLEX_CONTENT_URL: "http://content-api:8000/api/v0" 
    HOST_NICKNAME: "local"
    TILED_KEY: "${TILED_KEY}"

services:

########################## LABELMAKER ##########################
  labelmaker:
    restart: "unless-stopped"
    container_name: "dash-label"
    build: 
      context: 'front/'
      dockerfile: 'docker/Dockerfile'
    environment:
      *commonEnvironment
    volumes:
      - ./data:/app/work/data
      - ./front/src:/app/work/src
    ports:
      - '8057:8057'
    networks:
      - computing_api_default
    depends_on:
      - splash


##########################  MLCOACH   ##########################

  # mlcoach:
  #   restart: "unless-stopped"
  #   container_name: "mlcoach"
  #   build:
  #     context: "../mlex_mlcoach/"
  #     dockerfile: "docker/Dockerfile"
  #   environment:
  #     DATA_DIR: "${PWD}/data/"
  #     HOST_NICKNAME: "local"
  #   volumes:
  #     - ${PWD}/data:/app/work/data
  #     - ../mlex_mlcoach/src:/app/work/src
  #   ports:
  #     - "8062:8062"
  #   networks:
  #     - computing_api_default
  #   depends_on:
  #     - labelmaker

########################  DATA CLINIC ##########################

  data_clinic:
    restart: "unless-stopped"
    container_name: "data_clinic"
    build:
      context: "../mlex_data_clinic/"
      dockerfile: "docker/Dockerfile"
    environment:
      *commonEnvironment
    volumes:
      - ${PWD}/data:/app/work/data
      - ../mlex_data_clinic/src:/app/work/src
    ports:
      - 127.0.0.1:8072:8050
    networks:
      - computing_api_default
    depends_on:
      - labelmaker

########################### SPLASH ##############################

  splash:
    container_name: "splash"
    build:
      context: '../splash-ml/'
      dockerfile: 'Dockerfile'
    ports:
      - '8087:80'
    environment:
       APP_MODULE: "tagging.api:app"
       LOGLEVEL: DEBUG
       MONGO_DB_URI: ${MONGO_DB_URI}
       MAX_WORKERS: 1
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true
