version: '3'

services:

########################## LABELMAKER ##########################
  labelmaker:
    restart: "unless-stopped"
    container_name: "dash-label"
    build: 
      context: 'front/'
      dockerfile: 'docker/Dockerfile'
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ./data:/app/work/data
      - ./front/src:/app/work/src
    ports:
      - '8057:8057'
    networks:
      - computing_api_default

  api:
    restart: "unless-stopped"
    container_name: "labelmaker-api"
    build:
      context: "api/"
      dockerfile: "docker/Dockerfile"
    ports:
      - "8005:8005"
    networks:
      - computing_api_default

##########################  MLCOACH   ##########################

  mlcoach:
    restart: "unless-stopped"
    container_name: "mlcoach"
    build:
      context: "../mlex_mlcoach/"
      dockerfile: "docker/Dockerfile"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - "8062:8062"
    networks:
      - computing_api_default

########################  DATA CLINIC ##########################

  data_clinic:
    restart: "unless-stopped"
    container_name: "data_clinic"
    build:
      context: "../mlex_data_clinic/"
      dockerfile: "docker/Dockerfile"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - "8072:8072"
    networks:
      - computing_api_default


networks:
  computing_api_default:
    external: true
