version: '3.7'

x-environment: &commonEnvironment
    DATA_DIR: "${PWD}/data/"
    PROJECT_ID: "-1"
    MLCOACH_URL: "http://localhost:8062"
    DATA_CLINIC_URL: "http://localhost:8072"
    LATENT_SPACE_EXPLORER_URL: "http://localhost:8092"
    SPLASH_URL: "http://splash:80/api/v0"
    MLEX_COMPUTE_URL: "http://job-service:8080/api/v0"
    MLEX_CONTENT_URL: "http://content-api:8000/api/v0" 
    HOST_NICKNAME: "local"
    TILED_KEY: "${TILED_KEY}"
    DEFAULT_TILED_URI: "${DEFAULT_TILED_URI}"

services:

  labelmaker:
    restart: "unless-stopped"
    container_name: "dash-label"
   image: ghcr.io/taxe10/dash_labelmaker_demo:main
    environment:
      *commonEnvironment
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - 127.0.0.1:8057:8057
    networks:
      - computing_api_default
    depends_on:
      - splash

  mlcoach:
    restart: "unless-stopped"
    container_name: "mlcoach"
    image: ghcr.io/taxe10/mlex_mlcoach:main
    environment:
      *commonEnvironment
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - 127.0.0.1:8062:8050
    networks:
      - computing_api_default
    depends_on:
      - labelmaker

  data_clinic:
    restart: "unless-stopped"
    container_name: "data_clinic"
    image: ghcr.io/taxe10/mlex_data_clinic:master
    environment:
      *commonEnvironment
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - 127.0.0.1:8072:8050
    networks:
      - computing_api_default
    depends_on:
      - labelmaker
  
  latent_space_explorer:
    restart: "unless-stopped"
    container_name: "latent_space_explorer"
    image: ghcr.io/runboj/mlex_latent_explorer:main
    environment:
      *commonEnvironment
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - 127.0.0.1:8092:8070
    networks:
      - computing_api_default
    depends_on:
      - labelmaker

  splash:
    image: ghcr.io/als-computing/splash-ml:master
    environment:
       APP_MODULE: "tagging.api:app"
       LOGLEVEL: DEBUG
       MONGO_DB_URI: ${MONGO_DB_URI}
       MAX_WORKERS: 1
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true