version: '3'

services:
    front-end:
        restart: "unless-stopped"
        container_name: "dash-label"
        build: 
            context: 'front/'
            dockerfile: 'docker/Dockerfile'
        command: 'python src/labelmaker.py'
        volumes:
            - "${PWD}/data:/app/work/data"
            - "./front/src:/app/work/src"
        ports:
            - '8050:8050'