version: '3'

services:

########################## LABELMAKER ##########################
  labelmaker:
    restart: "unless-stopped"
    container_name: "dash-label"
    build: 
      context: 'front/'
      dockerfile: 'docker/Dockerfile'
    environment:
      DATA_DIR: "${PWD}/data/"
      TILED_KEY: "${TILED_KEY}"
      MLCOACH_URL: "${MLCOACH_URL}"
      DATA_CLINIC_URL: "${DATA_CLINIC_URL}"
    volumes:
      - ./data:/app/work/data
      - ./front/src:/app/work/src
    ports:
      - '8057:8057'
    networks:
      - computing_api_default
    depends_on:
      - tiled-server
      - api
      - splash

  api:
    restart: "unless-stopped"
    container_name: "labelmaker-api"
    build:
      context: "api/"
      dockerfile: "docker/Dockerfile"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
    ports:
      - "8005:8005"
    networks:
      - computing_api_default

##########################  MLCOACH   ##########################

  mlcoach:
    restart: "unless-stopped"
    container_name: "mlcoach"
    build:
      context: "../mlex_mlcoach/"
      dockerfile: "docker/Dockerfile"
    environment:
      DATA_DIR: "${PWD}/data/"
      HOST_NICKNAME: "${HOST_NICKNAME}"
    volumes:
      - ${PWD}/data:/app/work/data
      - ../mlex_mlcoach/src:/app/work/src
    ports:
      - "8062:8062"
    networks:
      - computing_api_default
    depends_on:
      - labelmaker

########################  DATA CLINIC ##########################

  data_clinic:
    restart: "unless-stopped"
    container_name: "data_clinic"
    build:
      context: "../mlex_data_clinic/"
      dockerfile: "docker/Dockerfile"
    environment:
      DATA_DIR: "${PWD}/data/"
      HOST_NICKNAME: "${HOST_NICKNAME}"
    volumes:
      - ${PWD}/data:/app/work/data
      - ../mlex_data_clinic/src:/app/work/src
    ports:
      - "8072:8072"
    networks:
      - computing_api_default
    depends_on:
      - labelmaker


########################### TILED ##############################

  tiled-server:
    image: ghcr.io/bluesky/tiled:v0.1.0a74
    volumes:
      - ${PWD}/data:/deploy/data
      - ../mlex_tiled/config:/deploy/config
      - ../mlex_tiled/gunicorn_config.py:/app/docker/gunicorn_config.py
    environment:
      - TILED_CONFIG=/deploy/config/config.yml
    networks:
      - computing_api_default

########################### SPLASH ##############################

  mongo_mlex: 
    image: mongo
    restart: always
    container_name: "mongodb_mlex"
    working_dir: "/mongodbdata/"
    volumes:
      - "./mongodbdata/:/data/db"
    networks:
      - computing_api_default

  splash:
    container_name: "splash"
    build:
      context: '../splash-ml/'
      dockerfile: 'Dockerfile'
    depends_on:
      - "mongo_mlex"
    ports:
      - '8087:80'
    environment:
       APP_MODULE: "tagging.api:app"
       LOGLEVEL: DEBUG
       MONGO_DB_URI: mongodb://mongodb_mlex:27017/tagging
       MAX_WORKERS: 1
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true
