version: '3.7'

x-environment: &commonEnvironment
    DIR_MOUNT: "${DATA_DIR}"
    DATA_DIR: "/app/work/data"
    PROJECT_ID: "-1"
    MLCOACH_URL: ${MLCOACH_URL}
    DATA_CLINIC_URL: ${DATA_CLINIC_URL}
    LATENT_SPACE_EXPLORER_URL: ${LATENT_SPACE_EXPLORER_URL}
    SPLASH_URL: ${SPLASH_URL}
    MLEX_COMPUTE_URL: ${MLEX_COMPUTE_URL}
    MLEX_CONTENT_URL: ${MLEX_CONTENT_URL}
    HOST_NICKNAME: "local"
    TILED_KEY: "${TILED_KEY}"
    DEFAULT_TILED_URI: "${DEFAULT_TILED_URI}"
    APP_HOST: "0.0.0.0"
    APP_PORT: "8050"

services:

  # MongoDB
  mongodb_tmp:
    image: mongo:4.4
    container_name: "mongodb_tmp"
    working_dir: /database/
    volumes:
      - "${PWD}/database:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    networks:
      - computing_api_default

  splash:
    image: ghcr.io/als-computing/splash-ml:master
    container_name: "splash_tmp"
    environment:
       APP_MODULE: "tagging.api:app"
       LOGLEVEL: DEBUG
       MONGO_DB_URI: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb_tmp:27017/tagging?authSource=admin
       MAX_WORKERS: 8
    ports:
      - "127.0.0.1:8085:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/splash_ml/docs#"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - computing_api_default

  labelmaker:
    container_name: "labelmaker"
    image: ghcr.io/mlexchange/dash_labelmaker_demo:main
    environment:
      *commonEnvironment
    volumes:
      - $DATA_DIR:/app/work/data
    ports:
      - 127.0.0.1:8057:8050
    depends_on:
      splash:
        condition: service_healthy
    networks:
      - computing_api_default

  mlcoach:
    container_name: "mlcoach"
    image: ghcr.io/mlexchange/mlex_mlcoach:main
    environment:
      *commonEnvironment
    volumes:
      - $DATA_DIR:/app/work/data
    ports:
      - 127.0.0.1:8062:8050
    depends_on:
      splash:
        condition: service_healthy
    networks:
      - computing_api_default

  data_clinic:
    container_name: "data_clinic"
    image: ghcr.io/mlexchange/mlex_data_clinic:master
    environment:
      *commonEnvironment
    volumes:
      - $DATA_DIR:/app/work/data
    ports:
      - 127.0.0.1:8072:8050
    networks:
      - computing_api_default

  # ML algorithms
  autoencoders:
    image: ghcr.io/mlexchange/mlex_pytorch_autoencoders:main

  classifier:
    image: ghcr.io/mlexchange/mlex_image_classification:main


networks:
  computing_api_default:
    external: true
