version: '3'

services:

########################## LABELMAKER ##########################
  labelmaker:
    image: mlexchange1/labelmaker:1.2
    restart: "unless-stopped"
    container_name: "dash-label"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ./data:/app/work/data
    ports:
      - '8057:8057'
    networks:
      - computing_api_default

  api:
    image: mlexchange1/labelmaker-api:latest
    restart: "unless-stopped"
    container_name: "labelmaker-api"
    ports:
      - "8005:8005"
    networks:
      - computing_api_default

##########################  MLCOACH   ##########################

  mlcoach:
    image: mlexchange1/mlcoach:1.1
    restart: "unless-stopped"
    container_name: "mlcoach"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - "8062:8062"
    networks:
      - computing_api_default

########################  DATA CLINIC ##########################

  data_clinic:
    image: mlexchange1/dataclinic:1.0
    restart: "unless-stopped"
    container_name: "data_clinic"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ${PWD}/data:/app/work/data
    ports:
      - "8072:8072"
    networks:
      - computing_api_default


networks:
  computing_api_default:
    external: true
