version: '3'

services:

########################## LABELMAKER ##########################
  labelmaker:
    image: mlexchange1/labelmaker:latest
    restart: "unless-stopped"
    container_name: "dash-label"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - "./data:/app/work/data"
      - "./front/src:/app/work/src"
    ports:
      - '8057:8057'
    networks:
      - computing_api_default

  api:
    image: mlexchange1/labelmaker-api:latest
    restart: "unless-stopped"
    container_name: "labelmaker-api"
    volumes:
      - ./api/src:/app/api/src
    ports:
      - "8005:8005"
    networks:
      - computing_api_default

##########################  MLCOACH   ##########################

  mlcoach:
    image: mlexchange1/mlcoach:latest
    restart: "unless-stopped"
    container_name: "mlcoach"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ${PWD}/data:/app/work/data
      - ${PWD}/../mlex_mlcoach/src:/app/work/mlcoach/src
    ports:
      - "8062:8062"
    networks:
      - computing_api_default

########################  DATA CLINIC ##########################

  data_clinic:
    image: mlexchange1/dataclinic:latest
    restart: "unless-stopped"
    container_name: "data_clinic"
    environment:
      DATA_DIR: "${PWD}/data/"
    volumes:
      - ${PWD}/data:/app/work/data
      - ${PWD}/../mlex_data_clinic/src:/app/work/data_clinic/src
    ports:
      - "8072:8072"
    networks:
      - computing_api_default


networks:
  computing_api_default:
    external: true
